export const BOOTSTAP_ACTION = "user/BOOTSTAP_ACTION";
export const SIGN_UP = "user/SIGN_UP";
export const SIGN_IN = "user/SIGN_IN";
export const SIGN_IN_WITH_GOOGLE = "user/SIGN_IN_WITH_GOOGLE";
export const SIGN_UP_WITH_BANK_ID= "user/SIGN_UP_WITH_BANK_ID";
export const SIGN_UP_WITH_SOCIALS= "user/SIGN_UP_WITH_SOCIALS";
export const SET_AUTH = "user/SET_AUTH";
export const SET_ACCOUNT = "user/SET_ACCOUNT";
export const SET_TOKEN = "user/SET_TOKEN";
export const SET_PROFILE = "user/SET_PROFILE";
export const CREATE_PROFILE = "user/CREATE_PROFILE";
export const CHANGE_PROFILE = "user/CHANGE_PROFILE";
export const SET_CHANGED_PROFILE = "user/SET_CHANGED_PROFILE";
export const LOG_OUT = "user/logout";
export const RESET_PASSWORD = "user/RESET_PASSWORD";
export const CHANGE_PASSWORD = "user/CHANGE_PASSWORD";
export const CHANGE_EMAIL = "user/CHANGE_EMAIL";
export const SET_USER_FETCHING = "user/SET_USER_FETCHING";
export const SET_TAB = "user/SET_TAB";
export const DELETE_ACCOUNT = "user/DELETE_ACCOUNT";
export const SET_RESPONSE_FROM_API = 'user/SET_RESPONSE_FROM_API'
export const CLEAN_AUTH_DATA = 'user/CLEAN_AUTH_DATA'
export const REQUEST_FOR_CHANGING_EMAIL = 'user/REQUEST_FOR_CHANGING_EMAIL'
export const REQUEST_FOR_CHANGING_PASSWORD = 'user/REQUEST_FOR_CHANGING_PASSWORD'
export const REQUEST_FOR_RESET_PASSWORD = 'user/REQUEST_FOR_RESET_PASSWORD'
export const CHECK_TOKEN_FOR_RESET_PASSWORD = 'user/CHECK_TOKEN_FOR_RESET_PASSWORD'
export const SET_SUCCESSFUL_CHANGE_EMAIL_OR_PASSWORD_TEXT = 'user/SET_SUCCESSFUL_CHANGE_EMAIL_OR_PASSWORD_TEXT'
export const CHECK_TOKEN = 'user/CHECK_TOKEN'
export const GET_QUIZ = 'user/GET_QUIZ'
export const SET_QUIZ = 'user/SET_QUIZ'
export const SET_QUIZ_IS_PASSED = 'user/SET_QUIZ_IS_PASSED'
export const CHECK_QUIZ_ANSWERS = 'user/CHECK_QUIZ_ANSWERS'
export const SET_QUIZ_ERRORS = 'user/SET_QUIZ_ERRORS'
export const GET_PROFILE_FROM_API = 'user/GET_PROFILE_FROM_API'
export const CHECK_ACTIVATION_TOKEN = 'user/CHECK_ACTIVATION_TOKEN'
export const CHECK_EMAIL_AND_PASSWORD = 'user/CHECK_EMAIL_AND_PASSWORD'
export const REQUEST_SIGN_IN_WITH_BANK_ID = 'user/REQUEST_SIGN_IN_WITH_BANK_ID'
export const SIGN_IN_WITH_BANK_ID = 'user/SIGN_IN_WITH_BANK_ID'
export const SET_TOKEN_FOR_QUIZ_SOCIALS_SIGN_IN = 'user/SET_TOKEN_FOR_QUIZ_SOCIALS_SIGN_IN'
export const SET_CURRENT_PATH = 'SET_CURRENT_PATH'
export const SET_IS_BANK_ID_RESIDENT = 'SET_IS_BANK_ID_RESIDENT'
export const SET_IS_AUTH_ON_AND_SAVE_USER_PROFILE = 'SET_IS_AUTH_ON_AND_SAVE_USER_PROFILE'
export const SET_BANK_ID_KEY = 'SET_BANK_ID_KEY'
export const REQUEST_SUBSCRIBE_LIST = 'user/REQUEST_SUBSCRIBE_LIST'
export const SET_SUBSCRIBE_LIST = 'user/SET_SUBSCRIBE_LIST'
export const CHANGE_UNSUBSCRIBE_LIST = 'user/CHANGE_UNSUBSCRIBE_LIST'
export const SET_UNSUBSCRIBE_LIST = 'user/SET_UNSUBSCRIBE_LIST'
export const SET_SOCIALS_KEY = 'SET_SOCIALS_KEY'

export const SAVE_EMAIL = 'user/SAVE_EMAIL'








export const SET_CAN_CHANGE_EMAIL = 'SET_CAN_CHANGE_EMAIL'
export const SET_CAN_CHANGE_PASSWORD = 'SET_CAN_CHANGE_PASSWORD'
export const SET_CAN_RESET_PASSWORD = 'SET_CAN_RESET_PASSWORD'





export const SET_LANGUAGE = "language/SET_LANGUAGE";
export const CHANGE_LANGUAGE = "language/CHANGE_LANGUAGE";

export const GET_FEATURED_CAMPAIGNS = "homePage/getFeaturedCampaigns";
export const GET_UPCOMING_CAMPAIGNS = "homePage/getUpcomingCampaigns";
export const GET_MORE_CAMPAIGNS = "homePage/getMoreCampaigns";
export const SET_IS_FETCHING_HOME_PAGE = "homePage/SET_IS_FETCHING_HOME_PAGE";

export const GET_ABOUT_US = "aboutUs/GET_ABOUT_US";
export const SET_ABOUT_US = "aboutUs/SET_ABOUT_US";
export const SET_EMAIL = "aboutUs/SET_EMAIL";
export const SET_IS_FETCHING_ABOUT_US = "aboutUs/SET_IS_FETCHING_ABOUT_US";

export const GET_RAISE_PAGE = "raise/GET_RAISE_PAGE";
export const SET_RAISE_PAGE = "raise/SET_RAISE_PAGE";
export const SEND_FORM = "raise/SEND_FORM";
export const SET_IS_FETCHING_RAISE_PAGE = "raise/SET_IS_FETCHING_RAISE_PAGE";
export const SET_SCROLL_TO_FORM = "raise/SET_SCROLL_TO_FORM"

export const GET_COMPANIES_LIST = "companies/GET_COMPANIES_LIST";
export const GET_COMPANIES_HEADER_LIST = "companies/GET_COMPANIES_HEADER_LIST";
export const GET_COMPANY_BY_SLAG = "companies/GET_COMPANY_BY_SLAG";
export const SET_COMPANIES_LIST = "companies/SET_COMPANIES_LIST";
export const SET_COMPANY_BY_ID = "companies/SET_COMPANY_BY_ID";
export const CLEAR_COMPANY = "companies/CLEAR_COMPANY";
export const SET_IS_FETCHING_COMPANIES = "companies/SET_IS_FETCHING_COMPANIES";
export const SET_ERROR_404_COMPANIES = "companies/SET_ERROR_404_COMPANIES";
export const SET_SELECTED_TAB = "companies/SET_SELECTED_TAB";
export const SET_INVEST_COMPANIES_LIST = "companies/SET_INVEST_COMPANIES_LIST";
export const SET_FILTER = "companies/SET_FILTER";
export const ADD_POST = "companies/ADD_POST";
export const GET_POSTS = "companies/GET_POSTS";
export const SET_POSTS = "companies/SET_POSTS";
export const ADD_FAQ_ANSWER = "companies/ADD_FAQ_ANSWER";
export const RESET_COMPANY_TAB = "companies/RESET_COMPANY_TAB";
export const RESET_COMPANY_LIST = "companies/RESET_COMPANY_LIST";
export const IS_MORE_COMPANIES = "companies/IS_MORE_COMPANIES";
export const MAKE_PAYMENT = "companies/MAKE_PAYMENT";
export const GET_COMPANY_BY_NAME = "companies/GET_COMPANY_BY_NAME";
export const GET_SEARCH_CAMPAIGNS = "companies/GET_SEARCH_CAMPAIGNS";
export const SET_SEARCH_CAMPAIGNS = "companies/SET_SEARCH_CAMPAIGNS";
export const CLEAN_SEARCH_CAMPAIGNS = "companies/CLEAN_SEARCH_CAMPAIGNS";
export const SET_CAMPAIGN_SEARCH_QUERY = "companies/SET_CAMPAIGN_SEARCH_QUERY";
export const SET_CAMPAIGN_OFFSET = "companies/SET_CAMPAIGN_OFFSET";


export const SET_IS_REDIRECT = 'companies/SET_IS_REDIRECT'

export const GET_HOME_PAGE = "homePage/GET_HOME_PAGE";
export const SET_HOME_PAGE = "homePage/SET_HOME_PAGE";

export const SET_SHOW_SIGN_IN = "authPopupWindows/SET_SHOW_SIGN_IN";
export const SET_SHOW_SIGN_UP = "authPopupWindows/SET_SHOW_SIGN_UP";
export const SET_SHOW_SESSION_SIGN_UP = "authPopupWindows/SET_SHOW_SESSION_SIGN_UP";
export const SET_SHOW_RESET_PASSWORD =
  "authPopupWindows/SET_SHOW_RESET_PASSWORD";
export const SET_SHOW_SUCCESSFUL_SIGN_UP =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_SIGN_UP";
export const SET_SHOW_SUCCESSFUL_CAMPAIGN_REGISTRATION =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_CAMPAIGN_REGISTRATION";
export const SET_SHOW_SUCCESSFUL_INVESTMENT =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_INVESTMENT";
export const SET_SHOW_SUCCESSFUL_RESET_PASSWORD =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_RESET_PASSWORD";
export const SET_SHOW_SUCCESSFUL_DELETED_ACCOUNT =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_DELETED_ACCOUNT";
export const SET_SHOW_CONFIRMATION_OF_ACCOUNT_DELETING =
  "authPopupWindows/SET_SHOW_CONFIRMATION_OF_ACCOUNT_DELETING";
export const SET_SHOW_QUIZ_MODAL = "authPopupWindows/SET_SHOW_QUIZ_MODAL"
export const SET_SHOW_QUIZ_ERROR = "authPopupWindows/SET_SHOW_QUIZ_ERROR"
export const SET_SHOW_SUCCESSFUL_SUBSCRIBE =
    "authPopupWindows/SET_SHOW_SUCCESSFUL_SUBSCRIBE"
export const SET_SHOW_RAISE_ERROR = "authPopupWindows/SET_SHOW_RAISE_ERROR"
export const SET_SHOW_REQUEST_FOR_CHANGE = "authPopupWindows/SET_SHOW_REQUEST_FOR_CHANGE"
export const SET_SHOW_INVALID_TOKEN_MODAL = "authPopupWindows/SET_SHOW_INVALID_TOKEN_MODAL"
export const SET_SHOW_SUCCESSFUL_CHANGE_EMAIL_OR_PASSWORD = "authPopupWindows/SET_SHOW_SUCCESSFUL_CHANGE_EMAIL_OR_PASSWORD"
export const SET_SHOW_DENY_DELETING_ACCOUNT = "authPopupWindows/SET_SHOW_DENY_DELETING_ACCOUNT"
export const SET_SHOW_SUCCESSFUL_FAQ_POST = "authPopupWindows/SET_SHOW_SUCCESSFUL_FAQ_POST"
export const SET_SHOW_DATA_LOSS_WARNING = "authPopupWindows/SET_SHOW_DATA_LOSS_WARNING"
export const SET_SHOW_REQUEST_FOR_CHANGE_PASSWORD = "authPopupWindows/SET_SHOW_REQUEST_FOR_CHANGE_PASSWORD"
export const SET_SHOW_REQUEST_FOR_CHANGE_EMAIL = "authPopupWindows/SET_SHOW_REQUEST_FOR_CHANGE_EMAIL"
export const SET_SHOW_SUCCESSFUL_FIRST_LOGIN = "authPopupWindows/SET_SHOW_SUCCESSFUL_FIRST_LOGIN"
export const SET_SHOW_POSTAL_CODE_NOTIFICATION = "authPopupWindows/SET_SHOW_POSTAL_CODE_NOTIFICATION"
export const SET_SHOW_COMPLETE_BANK_ID_REGISTRATION = "authPopupWindows/SET_SHOW_COMPLETE_BANK_ID_REGISTRATION"
export const SET_SHOW_COMPLETE_SOCIALS_REGISTRATION = "authPopupWindows/SET_SHOW_COMPLETE_SOCIALS_REGISTRATION"
export const SET_SHOW_SUCCESSFUL_QUIZ_MESSAGE = "authPopupWindows/SET_SHOW_SUCCESSFUL_QUIZ_MESSAGE"
export const SET_SHOW_OPTIONAL_QUIZ_MESSAGE = "authPopupWindows/SET_SHOW_OPTIONAL_QUIZ_MESSAGE"
export const SET_SHOW_DATA_LOSS_WARNING_FROM_PROFILE = "authPopupWindows/SET_SHOW_DATA_LOSS_WARNING_FROM_PROFILE"








export const SET_SHOW_COOKIE = "SET_SHOW_COOKIE"

export const GET_LAUNCHING_SOON_POSTS = "launchingSoon/GET_POSTS";
export const SET_LAUNCHING_SOON_POSTS = "launchingSoon/SET_POSTS";
export const SET_IS_FETCHING_LAUNCHING_SOON =
  "launchingSoon/SET_IS_FETCHING_LAUNCHING_SOON";

export const SET_NOTIFICATION_STATUS = "alert/SET_NOTIFICATION_STATUS";
export const SET_NOTIFICATION_MESSAGE = "alert/SET_NOTIFICATION_MESSAGE";
export const SET_NOTIFICATION_TITLE = "alert/SET_NOTIFICATION_TITLE";

export const GET_DOCUMENTS = "documents/GET_DOCUMENTS";
export const SET_DOCUMENTS = "documents/SET_DOCUMENTS";

export const ERROR = "ERROR";

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR'
export const SET_RAISE_ERROR = 'SET_RAISE_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_AUTH_EMAIL_ERROR = 'CLEAR_AUTH_EMAIL_ERROR'
export const SET_AUTH_PASSWORD_ERROR = 'CLEAR_AUTH_PASSWORD_ERROR'
export const SET_AUTH_USER_ERROR = 'CLEAR_AUTH_USER_ERROR'
export const SET_AUTH_OLD_PASSWORD_ERROR = 'CLEAR_AUTH_OLD_PASSWORD_ERROR'
export const SET_AUTH_NEW_PASSWORD1_ERROR = 'CLEAR_AUTH_PASSWORD1_ERROR'
export const SET_AUTH_NEW_PASSWORD2_ERROR = 'CLEAR_AUTH_PASSWORD2_ERROR'
export const SET_AUTH_SOCIAL_ACCOUNT_ERROR = 'SET_AUTH_SOCIAL_ACCOUNT_ERROR'

export const SET_PROFILE_FIRST_NAME_ERROR = 'SET_PROFILE_FIRST_NAME_ERROR'
export const SET_PROFILE_SECOND_NAME_ERROR = 'SET_PROFILE_SECOND_NAME_ERROR'
export const SET_PROFILE_COUNTRY_ERROR = 'SET_PROFILE_COUNTRY_ERROR'
export const SET_PROFILE_CITY_ERROR = 'SET_PROFILE_CITY_ERROR'
export const SET_PROFILE_ADDRESS_ERROR = 'SET_PROFILE_ADDRESS_ERROR'
export const SET_PROFILE_PERSONAL_ID_ERROR = 'SET_PROFILE_PERSONAL_ID_ERROR'
export const SET_PROFILE_PHONE_ERROR = 'SET_PROFILE_PHONE_ERROR'
export const SET_PROFILE_DATE_OF_BIRTH_ERROR = 'SET_PROFILE_DATE_OF_BIRTH_ERROR'
export const SET_PROFILE_ZIP_ERROR = 'SET_PROFILE_ZIP_ERROR'
export const SET_PROFILE_AVATAR_ERROR = 'SET_PROFILE_AVATAR_ERROR'
export const SET_PROFILE_EMAIL_ERROR = 'SET_PROFILE_EMAIL_ERROR'
export const CLEAR_PROFILE_ERRORS = 'CLEAR_PROFILE_ERRORS'



export const SET_FORM1_FIRST_NAME_ERROR = 'SET_FORM1_FIRST_NAME_ERROR'
export const SET_FORM1_SECOND_NAME_ERROR = 'SET_FORM1_SECOND_NAME_ERROR'
export const SET_FORM1_EMAIL_ERROR = 'SET_FORM1_EMAIL_ERROR'
export const SET_FORM1_PHONE_ERROR = 'SET_FORM1_PHONE_ERROR'
export const SET_FORM1_COUNTRY_ERROR = 'SET_FORM1_COUNTRY_ERROR'
export const SET_FORM2_COMPANY_NAME_ERROR = 'SET_FORM2_COMPANY_NAME_ERROR'
export const SET_FORM2_COMPANY_FORM_ERROR = 'SET_FORM2_COMPANY_FORM_ERROR'
export const SET_FORM2_ROLE_ERROR = 'SET_FORM2_ROLE_ERROR'
export const SET_FORM2_SHARE_PRICE_ERROR = 'SET_FORM2_SHARE_PRICE_ERROR'
export const SET_FORM2_REVENUE_ERROR = 'SET_FORM2_REVENUE_ERROR'
export const SET_FORM2_AMOUNT_ERROR = 'SET_FORM2_AMOUNT_ERROR'
export const SET_FORM3_WEBSITE_ERROR = 'SET_FORM3_WEBSITE_ERROR'
export const SET_FORM3_VIDEO_PREVIEW_ERROR = 'SET_FORM3_VIDEO_PREVIEW_ERROR'
export const SET_FORM3_SOCIAL_ONE_ERROR = 'SET_FORM3_SOCIAL_ONE_ERROR'
export const SET_FORM3_SOCIAL_TWO_ERROR = 'SET_FORM3_SOCIAL_TWO_ERROR'
export const SET_FORM3_SOCIAL_THREE_ERROR = 'SET_FORM3_SOCIAL_THREE_ERROR'
export const SET_FORM3_FOLLOWERS_ONE_ERROR = 'SET_FORM3_FOLLOWERS_ONE_ERROR'
export const SET_FORM3_FOLLOWERS_TWO_ERROR = 'SET_FORM3_FOLLOWERS_TWO_ERROR'
export const SET_FORM3_FOLLOWERS_THREE_ERROR = 'SET_FORM3_FOLLOWERS_THREE_ERROR'


export const GET_FAQ_CATEGORIES = 'faq/GET_FAQ_CATEGORIES'
export const SET_FAQ_CATEGORIES = 'faq/SET_FAQ_CATEGORIES'
export const SET_FAQ_FETCHING = 'faq/SET_FAQ_FETCHING'
export const FAQ_SEARCH = 'faq/FAQ_SEARCH'
export const SAVE_FAQ_SEARCH = 'faq/SAVE_FAQ_SEARCH'
export const GET_ONE_CATEGORY = 'faq/GET_ONE_CATEGORY'
export const SAVE_ONE_CATEGORY = 'faq/SAVE_ONE_CATEGORY'
export const SET_CURRENT_CATEGORY = 'faq/SET_CURRENT_CATEGORY'
export const SET_CURRENT_QUESTION = 'faq/SET_CURRENT_QUESTION'
export const GET_QUESTION = 'faq/GET_QUESTION'
export const SET_QUESTION = 'faq/SET_QUESTION'
export const SET_404_IN_QUESTION = 'faq/SET_404_IN_QUESTION'
