export const BOOTSTAP_ACTION = "user/BOOTSTAP_ACTION";
export const SIGN_UP = "user/SIGN_UP";
export const SIGN_IN = "user/SIGN_IN";
export const SET_AUTH = "user/SET_AUTH";
export const SET_ACCOUNT = "user/SET_ACCOUNT";
export const SET_TOKEN = "user/SET_TOKEN";
export const SET_PROFILE = "user/SET_PROFILE";
export const CREATE_PROFILE = "user/CREATE_PROFILE";
export const CHANGE_PROFILE = "user/CHANGE_PROFILE";
export const SET_CHANGED_PROFILE = "user/SET_CHANGED_PROFILE";
export const LOG_OUT = "user/logout";
export const RESET_PASSWORD = "user/RESET_PASSWORD";
export const CHANGE_PASSWORD = "user/CHANGE_PASSWORD";
export const CHANGE_EMAIL = "user/CHANGE_EMAIL";
export const SET_USER_FETCHING = "user/SET_USER_FETCHING";
export const SET_TAB = "user/SET_TAB";
export const DELETE_ACCOUNT = "user/DELETE_ACCOUNT";
export const SET_RESPONSE_FROM_API = 'user/SET_RESPONSE_FROM_API'

export const REQUEST_FOR_CHANGING_EMAIL = 'user/REQUEST_FOR_CHANGING_EMAIL'
export const REQUEST_FOR_CHANGING_PASSWORD = 'user/REQUEST_FOR_CHANGING_PASSWORD'


export const SET_CAN_CHANGE_EMAIL = 'SET_CAN_CHANGE_EMAIL'


export const SET_LANGUAGE = "language/SET_LANGUAGE";
export const CHANGE_LANGUAGE = "language/CHANGE_LANGUAGE";

export const GET_FEATURED_CAMPAIGNS = "homePage/getFeaturedCampaigns";
export const GET_UPCOMING_CAMPAIGNS = "homePage/getUpcomingCampaigns";
export const GET_MORE_CAMPAIGNS = "homePage/getMoreCampaigns";
export const SET_IS_FETCHING_HOME_PAGE = "homePage/SET_IS_FETCHING_HOME_PAGE";

export const GET_ABOUT_US = "aboutUs/GET_ABOUT_US";
export const SET_ABOUT_US = "aboutUs/SET_ABOUT_US";
export const SET_EMAIL = "aboutUs/SET_EMAIL";
export const SET_IS_FETCHING_ABOUT_US = "aboutUs/SET_IS_FETCHING_ABOUT_US";

export const GET_RAISE_PAGE = "raise/GET_RAISE_PAGE";
export const SET_RAISE_PAGE = "raise/SET_RAISE_PAGE";
export const SEND_FORM = "raise/SEND_FORM";
export const SET_IS_FETCHING_RAISE_PAGE = "raise/SET_IS_FETCHING_RAISE_PAGE";

export const GET_COMPANIES_LIST = "companies/GET_COMPANIES_LIST";
export const GET_COMPANIES_HEADER_LIST = "companies/GET_COMPANIES_HEADER_LIST";
export const GET_COMPANY_BY_ID = "companies/GET_COMPANY_BY_ID";
export const SET_COMPANIES_LIST = "companies/SET_COMPANIES_LIST";
export const SET_COMPANY_BY_ID = "companies/SET_COMPANY_BY_ID";
export const CLEAR_COMPANY = "companies/CLEAR_COMPANY";
export const SET_IS_FETCHING_COMPANIES = "companies/SET_IS_FETCHING_COMPANIES";
export const SET_ERROR_404_COMPANIES = "companies/SET_ERROR_404_COMPANIES";
export const SET_SELECTED_TAB = "companies/SET_SELECTED_TAB";
export const SET_INVEST_COMPANIES_LIST = "companies/SET_INVEST_COMPANIES_LIST";
export const SET_FILTER = "companies/SET_FILTER";
export const ADD_POST = "companies/ADD_POST";
export const GET_POSTS = "companies/GET_POSTS";
export const SET_POSTS = "companies/SET_POSTS";
export const ADD_FAQ_ANSWER = "companies/ADD_FAQ_ANSWER";
export const RESET_COMPANY_TAB = "companies/RESET_COMPANY_TAB";
export const RESET_COMPANY_LIST = "companies/RESET_COMPANY_LIST";
export const IS_MORE_COMPANIES = "companies/IS_MORE_COMPANIES";
export const MAKE_PAYMENT = "companies/MAKE_PAYMENT";

export const GET_HOME_PAGE = "homePage/GET_HOME_PAGE";
export const SET_HOME_PAGE = "homePage/SET_HOME_PAGE";

export const SET_SHOW_SIGN_IN = "authPopupWindows/SET_SHOW_SIGN_IN";
export const SET_SHOW_SIGN_UP = "authPopupWindows/SET_SHOW_SIGN_UP";
export const SET_SHOW_RESET_PASSWORD =
  "authPopupWindows/SET_SHOW_RESET_PASSWORD";
export const SET_SHOW_SUCCESSFUL_SIGN_UP =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_SIGN_UP";
export const SET_SHOW_SUCCESSFUL_CAMPAIGN_REGISTRATION =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_CAMPAIGN_REGISTRATION";
export const SET_SHOW_SUCCESSFUL_INVESTMENT =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_INVESTMENT";
export const SET_SHOW_SUCCESSFUL_RESET_PASSWORD =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_RESET_PASSWORD";
export const SET_SHOW_SUCCESSFUL_DELETED_ACCOUNT =
  "authPopupWindows/SET_SHOW_SUCCESSFUL_DELETED_ACCOUNT";
export const SET_SHOW_CONFIRMATION_OF_ACCOUNT_DELETING =
  "authPopupWindows/SET_SHOW_CONFIRMATION_OF_ACCOUNT_DELETING";
export const SET_SHOW_QUIZ_MODAL = "authPopupWindows/SET_SHOW_QUIZ_MODAL"
export const SET_SHOW_QUIZ_ERROR = "authPopupWindows/SET_SHOW_QUIZ_ERROR"
export const SET_SHOW_SUCCESSFUL_SUBSCRIBE =
    "authPopupWindows/SET_SHOW_SUCCESSFUL_SUBSCRIBE"
export const SET_SHOW_RAISE_ERROR = "authPopupWindows/SET_SHOW_RAISE_ERROR"

export const GET_LAUNCHING_SOON_POSTS = "launchingSoon/GET_POSTS";
export const SET_LAUNCHING_SOON_POSTS = "launchingSoon/SET_POSTS";
export const SET_IS_FETCHING_LAUNCHING_SOON =
  "launchingSoon/SET_IS_FETCHING_LAUNCHING_SOON";

export const SET_NOTIFICATION_STATUS = "alert/SET_NOTIFICATION_STATUS";
export const SET_NOTIFICATION_MESSAGE = "alert/SET_NOTIFICATION_MESSAGE";
export const SET_NOTIFICATION_TITLE = "alert/SET_NOTIFICATION_TITLE";

export const GET_DOCUMENTS = "documents/GET_DOCUMENTS";
export const SET_DOCUMENTS = "documents/SET_DOCUMENTS";

export const ERROR = "ERROR";

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR'
export const SET_RAISE_ERROR = 'SET_RAISE_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_AUTH_EMAIL_ERROR = 'CLEAR_AUTH_EMAIL_ERROR'
export const SET_AUTH_PASSWORD_ERROR = 'CLEAR_AUTH_PASSWORD_ERROR'
export const SET_AUTH_USER_ERROR = 'CLEAR_AUTH_USER_ERROR'
export const SET_AUTH_OLD_PASSWORD_ERROR = 'CLEAR_AUTH_OLD_PASSWORD_ERROR'
export const SET_AUTH_NEW_PASSWORD1_ERROR = 'CLEAR_AUTH_PASSWORD1_ERROR'
export const SET_AUTH_NEW_PASSWORD2_ERROR = 'CLEAR_AUTH_PASSWORD2_ERROR'
export const SET_PROFILE_FIRST_NAME_ERROR = 'SET_PROFILE_FIRST_NAME_ERROR'
export const SET_PROFILE_SECOND_NAME_ERROR = 'SET_PROFILE_SECOND_NAME_ERROR'
export const SET_PROFILE_COUNTRY_ERROR = 'SET_PROFILE_COUNTRY_ERROR'
export const SET_PROFILE_CITY_ERROR = 'SET_PROFILE_CITY_ERROR'
export const SET_PROFILE_ADDRESS_ERROR = 'SET_PROFILE_ADDRESS_ERROR'
export const SET_PROFILE_PERSONAL_ID_ERROR = 'SET_PROFILE_PERSONAL_ID_ERROR'
export const SET_PROFILE_PHONE_ERROR = 'SET_PROFILE_PHONE_ERROR'
export const SET_PROFILE_DATE_OF_BIRTH_ERROR = 'SET_PROFILE_DATE_OF_BIRTH_ERROR'
export const SET_FORM1_FIRST_NAME_ERROR = 'SET_FORM1_FIRST_NAME_ERROR'
export const SET_FORM1_SECOND_NAME_ERROR = 'SET_FORM1_SECOND_NAME_ERROR'
export const SET_FORM1_EMAIL_ERROR = 'SET_FORM1_EMAIL_ERROR'
export const SET_FORM1_PHONE_ERROR = 'SET_FORM1_PHONE_ERROR'
export const SET_FORM1_COUNTRY_ERROR = 'SET_FORM1_COUNTRY_ERROR'
export const SET_FORM2_COMPANY_NAME_ERROR = 'SET_FORM2_COMPANY_NAME_ERROR'
export const SET_FORM2_COMPANY_FORM_ERROR = 'SET_FORM2_COMPANY_FORM_ERROR'
export const SET_FORM2_ROLE_ERROR = 'SET_FORM2_ROLE_ERROR'
export const SET_FORM2_SHARE_PRICE_ERROR = 'SET_FORM2_SHARE_PRICE_ERROR'
export const SET_FORM2_REVENUE_ERROR = 'SET_FORM2_REVENUE_ERROR'
export const SET_FORM2_AMOUNT_ERROR = 'SET_FORM2_AMOUNT_ERROR'
export const SET_FORM3_WEBSITE_ERROR = 'SET_FORM3_WEBSITE_ERROR'
export const SET_FORM3_VIDEO_PREVIEW_ERROR = 'SET_FORM3_VIDEO_PREVIEW_ERROR'
export const SET_FORM3_SOCIAL_ONE_ERROR = 'SET_FORM3_SOCIAL_ONE_ERROR'
export const SET_FORM3_SOCIAL_TWO_ERROR = 'SET_FORM3_SOCIAL_TWO_ERROR'
export const SET_FORM3_SOCIAL_THREE_ERROR = 'SET_FORM3_SOCIAL_THREE_ERROR'
export const SET_FORM3_FOLLOWERS_ONE_ERROR = 'SET_FORM3_FOLLOWERS_ONE_ERROR'
export const SET_FORM3_FOLLOWERS_TWO_ERROR = 'SET_FORM3_FOLLOWERS_TWO_ERROR'
export const SET_FORM3_FOLLOWERS_THREE_ERROR = 'SET_FORM3_FOLLOWERS_THREE_ERROR'