trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn build:dev
  displayName: '[Dev] Yarn install and build'

- task: CopyFiles@2
  inputs:
    Contents: |
      '$(Agent.BuildDirectory)/.next/**'
      '$(Agent.BuildDirectory)/public/**'
      '$(Agent.BuildDirectory)/package.json'
      '$(Agent.BuildDirectory)/next.config.js'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'accumeo_next'